name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        #        platform: [macos-latest, ubuntu-20.04, windows-latest]
        platform: [ windows-latest ]

    name: Test `cargo check/test/build` on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./

      - run: |
          cargo check
          cargo test
          cargo build --release
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        #        platform: [macos-latest, ubuntu-20.04, windows-latest]
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable



      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Focus Assistant v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false